### ISSUE TITLE
i can't find detectron2\model_zoo\configs\common\optim.py file in this demo,but it has to be used in matting_inference()

### ISSUE THREAD

**Issue by marefakee** [YihanHu-2022/DiffMatte#10]

**Comment by YihanHu-2022** [comment]
This file is contained in your detectron2 package. Check it out in repo:[detectron2](https://github.com/facebookresearch/detectron2)

**Comment by YihanHu-2022** [comment]
https://github.com/facebookresearch/detectron2/blob/main/configs/common/optim.py
In case you still cannot find it. :(

**Comment by YihanHu-2022** [comment]
It will be nice if you can support this repo with a star :)
