### ISSUE TITLE
Cannot run the file run_one_image.py

### ISSUE THREAD

**Issue by thangnh0608** [YihanHu-2022/DiffMatte#6]
The command I used to tets Diff Matte:

`python run_one_image.py --model vitmatte-s --checkpoint-dir ./DiffMatte_ViTS_Com_1024.pth --image-dir 80209689_889049583_525_1_f_mask_0_person_6.png  --trimap-dir 80209689_889049583_525_1_f_mask_0_person_6.png --output-dir ./test_matting`

but get the error: run_one_image.py: error: unrecognized arguments: --model

can you help me to fix the issue?

**Comment by YihanHu-2022** [comment]
sorry for the late response, it seems that you are using the wrong command to run the demo code. We have fixed this command in run_one_image.py, hope this can help you. :)
